### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by wildan3105** [wildan3105/github-langs#1]
**Current behavior:**
Current style of the website is very standard. It's even too simple for this kind of website.

**Expected behavior:**
Any UI improvements are welcome ! You can add emoji (if it's good) i.e if the repo more than 100, you can beautify the footer, and other things.

**Comment by wildan3105** [comment]
Hi @PREMPRAKASHSINGH, thanks for the quick reply! Yes, you can categorize the emoji based on the amount of user's repo. If he has no repo, you can add :cry: emoji, if he/she has 100 repo, you can add :100:, etc. Please feel free to explore! :ok_hand:

**Comment by PREMPRAKASHSINGH** [comment]
Cool thanks!
Working on it 👍

**Comment by wildan3105** [comment]
If you don't mind, please beautify the search bar and button also :smile: @PREMPRAKASHSINGH. Thanks!

**Comment by PREMPRAKASHSINGH** [comment]
Sure 👍

**Comment by benjaminr177** [comment]
Are there any UI changes which still need a helping hand?

**Comment by wildan3105** [comment]
Yes @benjaminr177 ! You could test the site from mobile, it's bad :cry:, you could improve that one and also the position of avatar is not looked well. Another improvements are welcome :)

**Comment by benjaminr177** [comment]
Okay, I'll have a look!

**Comment by Trommelochse** [comment]
Would also love to contribute, but it seems like things are being taken care of :) Let me know if you can thik of anything else.

**Comment by wildan3105** [comment]
Okay @Trommelochse. Maybe I'll open up some issue(s). Still wait PR(s) from the first ones :+1:

**Comment by PREMPRAKASHSINGH** [comment]
![image](https://user-images.githubusercontent.com/14115048/31359885-900d6160-ad69-11e7-99ac-9a1d9698d194.png)

@wildan3105  How does it look? changed footer and search bar

**Comment by wildan3105** [comment]
Wow! That's awesome :+1: I really like the search bar. Will try this first :smile:

**Comment by PREMPRAKASHSINGH** [comment]
cool adding the emojis now. then will make a PR

**Comment by wildan3105** [comment]
Hi @Trommelochse, new issue about responsiveness is open! #15
