### ISSUE TITLE
Word 'language stats' disappear when toggling bar graph color 

### ISSUE THREAD

**Issue by wildan3105** [wildan3105/github-langs#101]
**Current behavior:**
Inconsistency display of word 'language stats' when toggling bar graph color

**Expected behavior:**
The word 'language stats' should show all the time and with the correct and suitable position.
![gif](https://media.giphy.com/media/duKwFR3uRMNV5JTtq8/giphy.gif)

**Steps to reproduce:**
Check for user, then toggling the bar graph color

**Comment by wildan3105** [comment]
Contributions are welcome to anybody! Just comment in this issue :)

**Comment by abhagsain** [comment]
On this issue! 😁

**Comment by MikeyAlmighty** [comment]
@wildan3105 Created PR :smile:

**Comment by wildan3105** [comment]
Thanks guys! But since @abhagsain commented first, I'd check on your PR first then go to the @MikeyAlmighty's
