### ISSUE TITLE
Create a css file with styles from the head of main.handlebars

### ISSUE THREAD

**Issue by juancuiule** [wildan3105/github-langs#11]
**Current behavior:**
The style of the website is inside a style tag in the head

**Expected behavior:**
It would be better to have it in another file

**Comment by juancuiule** [comment]
I'll be taking care of this in a moment

**Comment by wildan3105** [comment]
Hei @juancuiule, it would be better if any `inline-style` code in `main.handlebars` separated in external `css` file. Thanks very much!

**Comment by PREMPRAKASHSINGH** [comment]
@juancuiule  let me know if you need any help.

**Comment by juancuiule** [comment]
Hey @wildan3105 if this issue was solved by someone don't wait for my PR

**Comment by wildan3105** [comment]
Okay @juancuiule, it already solved by #13 and #14
