### ISSUE TITLE
Refactor error codes

### ISSUE THREAD

**Issue by wildan3105** [wildan3105/github-langs#112]
**Current behavior:**
Error codes spread in several file & format. No standard error is found.

**Expected behavior:**
Create a dedicated error codes type.

**Steps to reproduce:**
File to watch:
- `lib/app.js` in line 8, should check if `process.env.ENV` is set
- `lib/controller.js` in line 15, should read error types from dedicated file

**Comment by wildan3105** [comment]
Contributions are welcome to anybody! Just comment in this issue :)

**Comment by michjk** [comment]
Hi, I will try to solve this issue.

**Comment by wildan3105** [comment]
Hi @michjk. Thanks and I'll wait for your PR!

**Comment by michjk** [comment]
Hi,

Are the error only limited to the one inside the files to be watched? Or it is include other kind of error like 404, 500, and etc?

**Comment by wildan3105** [comment]
For now, it's only the files that I've stated (internal error), exclude http status code @michjk

**Comment by wildan3105** [comment]
Hi @michjk, are you still working on this issue?

**Comment by michjk** [comment]
I create the pull request. You may look if this is the expected solution.

**Comment by wildan3105** [comment]
I've commented on your PR. Please kindly check it @michjk

**Comment by wildan3105** [comment]
Solved by #118
