### ISSUE TITLE
Refactor emoji & response-statements

### ISSUE THREAD

**Issue by wildan3105** [wildan3105/github-langs#113]
**Current behavior:**
All emojis and response statements are found in `lib/controller.js`. This made the controlloer little bit dirty.

**Expected behavior:**
Create dedicated file to hold all emojis and statements.

**Comment by wildan3105** [comment]
Contributions are welcome to anybody! Just comment in this issue :)

**Comment by bkstephen** [comment]
I'd like to give this a try

**Comment by wildan3105** [comment]
Hi @bkstephen. Sure thing and I'll wait for your PR!

**Comment by wildan3105** [comment]
Fixed by #120
