### ISSUE TITLE
Refactor github API root url

### ISSUE THREAD

**Issue by wildan3105** [wildan3105/github-langs#114]
**Current behavior:**
All endpoint urls are defined and called inside `lib/controller.js`. 

**Expected behavior:**
It should be stored in a config file.

**Comment by wildan3105** [comment]
Contributions are welcome to anybody! Just comment in this issue :)

**Comment by mkiterian** [comment]
@wildan3105 I picked this up. Looking forward to the review

**Comment by wildan3105** [comment]
Hi @mkiterian, thanks for such a quick PR! I'll review the PR first :ok_hand:

**Comment by wildan3105** [comment]
Closed by #115
