### ISSUE TITLE
Make animated toggle color button

### ISSUE THREAD

**Issue by wildan3105** [wildan3105/github-langs#125]
**Current behavior:**
Currnet toggle button is static, which means not animated when switching chart type (colorful  / white).

![](https://media.giphy.com/media/WU0OtANFO30wagnOHL/giphy.gif)

**Expected behavior:**
It would be better to use animated toggle button, example using bootstrap: [bootstrap toggle](http://bootstraptoggle.com) Please also note to pay attention to the size and shape of the animated toggle button so it does not oversize compared to the download button next to the animated toggle button. 

![](https://media.giphy.com/media/XcAo9I1qa1SROkiMBR/giphy.gif)

**Comment by ibokg** [comment]
Can I take up this issue?

**Comment by wildan3105** [comment]
Hi @ibokg, yes go on@

**Comment by wildan3105** [comment]
Closed by #126
