### ISSUE TITLE
Create logo for the site based on text

### ISSUE THREAD

**Issue by wildan3105** [wildan3105/github-langs#131]
**Current behavior:**
There's no logo for this site **Github Language Checker**

**Expected behavior:**
It should be good and awesome if we have a nice and simple logo for this project.

**Steps to reproduce:**
This issue is only an initiative. Any suggestions are welcome. Let's discuss!

**Comment by RaviTejaCMS** [comment]
How about these?
![1](https://user-images.githubusercontent.com/13203149/66371398-a4d62100-e9c0-11e9-8958-b6f38fc53c82.png) 

![2](https://user-images.githubusercontent.com/13203149/66371405-a869a800-e9c0-11e9-9b06-27c887ce3b0a.png)

![3](https://user-images.githubusercontent.com/13203149/66371409-aacc0200-e9c0-11e9-87e2-6fa0357187c6.png)

**Comment by wildan3105** [comment]
Hi @RaviTejaCMS, thank you for the suggestion! But I personally think it'd be good if we could modify the text **Github Language Checker** instead of using additional image/logo. Example:

![](https://hacktoberfest.digitalocean.com/assets/logo-hf19-header-8245176fe235ab5d942c7580778a914110fa06a23c3d55bf40e2d061809d8785.svg)

or 

![](https://i.ibb.co/6rGs3Mj/hacktoberfest-checker.png)

Could you modify your suggestion? Thanks! :smiley:

**Comment by RaviTejaCMS** [comment]
How about these(Just gave it a try🧐) 
![1](https://user-images.githubusercontent.com/13203149/66375573-59754000-e9cb-11e9-8e41-bf09bc34c2ba.png)

![2](https://user-images.githubusercontent.com/13203149/66375574-59754000-e9cb-11e9-9963-3e3c7f1196e7.png)

![3](https://user-images.githubusercontent.com/13203149/66375575-5a0dd680-e9cb-11e9-952e-b5a7715a7c60.png)

![5](https://user-images.githubusercontent.com/13203149/66375576-5a0dd680-e9cb-11e9-950a-04742833e324.png)

**Comment by herdir** [comment]
![image](https://user-images.githubusercontent.com/5861911/66709244-6d6cc900-ed60-11e9-8d78-de35b1628a2a.png)

==========

![image](https://user-images.githubusercontent.com/5861911/66709254-a016c180-ed60-11e9-8b06-c854f0e98d2d.png)


==========

![image](https://user-images.githubusercontent.com/5861911/66709269-dce2b880-ed60-11e9-87c3-74e85064db87.png)

==========

![image](https://user-images.githubusercontent.com/5861911/66709279-06034900-ed61-11e9-906c-cb402d6b6422.png)

**Comment by wildan3105** [comment]
No longer relevant. I am closing this one.
