### ISSUE TITLE
always updating the css when doing npm start

### ISSUE THREAD

**Issue by wildan3105** [wildan3105/github-langs#145]
**Current behavior:**
When we're doing the `npm start` locally, it makes the following file to be changed `lib/public/css/screen/base.css` 

![changes](https://user-images.githubusercontent.com/7030099/94886849-d502b380-049e-11eb-85cf-55fed31e2786.png)

**Expected behavior:**
Running locally shouldn't change any file or we can add the file to be ignored.

**Steps to reproduce:**
Run `npm start`

**Comment by yerlantemir** [comment]
Hi, could you assign me?

**Comment by wildan3105** [comment]
yes, sure! feel free to reproduce on your local and come up with a PR! @yerlantemir

**Comment by urmauur** [comment]
Hi @wildan3105 I try running locally but always got `error_messages.CLIENT_ID_AND_CLIENT_SECRET_MISSING` also already add .env on the root folder, am I missing something?

**Comment by wildan3105** [comment]
oh sorry I changed the implementation of `dotenv` so right now no need to add `.env` file. Just running it like this: 
`CLIENT_ID=your_client_id CLIENT_SECRET=your_client_secret ENV=local npm start`

**Comment by urmauur** [comment]
> oh sorry I changed the implementation of `dotenv` so right now no need to add `.env` file. Just running it like this:
> `CLIENT_ID=your_client_id CLIENT_SECRET=your_client_secret ENV=local npm start`

yes running that's script everything good, but nothing happens on port 5000 on my browser.

**Comment by wildan3105** [comment]
Have you [generated](https://github.com/settings/applications/new) client_id and client_secret? Can you also try to **rm -rf node_modules/** and do the **npm install** again? 

The log should be like this if you've successfully run the repo locally:

![run](https://user-images.githubusercontent.com/7030099/94894723-279a9a80-04b4-11eb-8830-4db6c9798a96.png)

**Comment by wildan3105** [comment]
Ignore the different path of `lib/app.js` because currently, I'm refactoring the repo

**Comment by urmauur** [comment]
yes I've client_id and client_secret, Here my logs

<img width="512" alt="Screen Shot 2020-10-02 at 13 39 39" src="https://user-images.githubusercontent.com/10354610/94895042-c7582880-04b4-11eb-8ef8-eff448381b29.png">

**Comment by wildan3105** [comment]
Ok let's put this into separate issue while I'm trying to reproduce this locally @urmauur

**Comment by urmauur** [comment]
@wildan3105 sure, let me know if already update, I want to try to fix your gulp-sass,

**Comment by wildan3105** [comment]
Let's coordinate in https://github.com/wildan3105/github-langs/issues/151 @urmauur

**Comment by urmauur** [comment]
@wildan3105 @yerlantemir any update this issue, can i try ?

**Comment by wildan3105** [comment]
basically the rule of thumb is everyone is welcomed to make any PR but the priority is to the first claimer, in this case @yerlantemir 
but you're most welcome to create a PR @urmauur

**Comment by urmauur** [comment]
@wildan3105 make a PR https://github.com/wildan3105/github-langs/pull/153

**Comment by wildan3105** [comment]
acknowledged, will take a look later

**Comment by urmauur** [comment]
> acknowledged, will take a look later

👌🏻
