### ISSUE TITLE
Social media share button only show text on firefox

### ISSUE THREAD

**Issue by wildan3105** [wildan3105/github-langs#149]
**Current behavior:**
Browse using firefox, social media share button (tweet & share fb) only showing the text without the button. Take a look at the picture below:

![firefox](https://user-images.githubusercontent.com/7030099/94890000-3e3af480-04a8-11eb-9cba-45c6b10c21de.png)

**Expected behavior:**

It should be displayed with the button and logo like this:

![chrome](https://user-images.githubusercontent.com/7030099/94890032-4f840100-04a8-11eb-80b8-71dcc3086041.png)

**Steps to reproduce:**

Browse using firefox 71.0 (64-bit)

**Comment by arnxv0** [comment]
https://support.mozilla.org/en-US/questions/1129489 this might help?

**Comment by wildan3105** [comment]
Ah I see. Maybe it's because privacy-related policy that's applied on firefox. Do you mind replicating this to other browser? like edge and safari @arnxv0

**Comment by wildan3105** [comment]
Never mind it’s only happening on firefox. Going to close this issue. Thanks for the useful information @arnxv0 !

**Comment by arnxv0** [comment]
Happy to help :) @wildan3105
