### ISSUE TITLE
Add loading button while fetching the API

### ISSUE THREAD

**Issue by wildan3105** [wildan3105/github-langs#15]
**Current behavior:**
User need to know if the system is working. But right now, there is no sign to display that system is fetching data through API

**Expected behavior:**
Add loading button while fetching the API. Any images are welcome, but I prefer the simple one like [this](https://www.w3schools.com/howto/howto_css_loading_buttons.asp)

**Comment by gkrishnan724** [comment]
So Basically you would like the search button to change to `Loading` when it is retrieving data?

**Comment by wildan3105** [comment]
Not change, but below the `search` bar and button there will be a loading gif/image, showing that the system is retrieving data from API. After fetch is done, the loading gif/image will be hidden, changed by chart. Do you get that? @gkrishnan724.

**Comment by gkrishnan724** [comment]
Yeah I get it :)

**Comment by azharakbar** [comment]
@wildan3105 Hey, I get it ... I will be working on it ... :) 
Isnt it better .. if u convert this into a Single Page Application (SPA) ?

**Comment by wildan3105** [comment]
Hi @azharakbar, you could submit a PR when you're done. What library do you suggest for SPA? I don't think it's an urgent, but we could discuss about it :ok_hand:

**Comment by azharakbar** [comment]
I suggest jquery ... at the simplest .. and fastest way ... :)

**Comment by wildan3105** [comment]
Thanks for the suggestion @azharakbar, maybe the SPA discussion could be another issue. Right know I'm focusing solve the current issue(s) :+1: 
Or you could submit an issue about it if you'd like

**Comment by azharakbar** [comment]
Ok ... i will be working on this first .. :)

**Comment by azharakbar** [comment]
@wildan3105 Hey, I have added the PR ... pls look into it .. :)

**Comment by azharakbar** [comment]
@wildan3105 Hi, I have raised the new PR ... :)

**Comment by wildan3105** [comment]
Closed by #37
