### ISSUE TITLE
Cannot accessing the app on normal browsing mode

### ISSUE THREAD

**Issue by urmauur** [wildan3105/github-langs#152]
**Current behavior:**
`currently i run this script CLIENT_ID=xxx CLIENT_SECRET=xxx ENV=local npm start`

**Expected behavior:**
Available can access https://localhost:5000
<img width="498" alt="Screen Shot 2020-10-02 at 13 57 17" src="https://user-images.githubusercontent.com/10354610/94896234-333b9080-04b7-11eb-9108-09adfb229fda.png">

**Steps to reproduce:**
`npm install`
`CLIENT_ID=xxx CLIENT_SECRET=xxx ENV=local npm start`

**Comment by wildan3105** [comment]
Possible solution:
- list all the app that's running on a specific port using this command: lsof -i tcp:<port>
- if there's an app that's still running, kill the app using this command: sudo kill <ppid>
- then run the app again

@urmauur

**Comment by wildan3105** [comment]
If you see the app is already running on a specific port (by doing `lsof -i tcp:<port>`), try to access it via a private mode browser because my above suggestion is only for this error:
`Nodemon: Error: listen EADDRINUSE: address already in use :::5000`

**Comment by urmauur** [comment]
> Possible solution:
> 
> * list all the app that's running on a specific port using this command: `lsof -i tcp:<port>`
> * if there's an app that's still running, kill the app using this command: `sudo kill <pid>`
> * then run the app again
> * try to browse on the private mode
> 
> @urmauur

oh shit @wildan3105 only private I can access

**Comment by wildan3105** [comment]
yeah so the problem is solved right? but still need to find a rootcause why is it not working on normal mode. you can close this one if you want to :+1:

**Comment by wildan3105** [comment]
or change this issue to be: `cannot running the app on normal browsing mode` and try to solve it :grin:

**Comment by urmauur** [comment]
After clear cache browse everything run normally on `localhost:5000` @wildan3105
