### ISSUE TITLE
Watch changes file SCSS

### ISSUE THREAD

**Issue by urmauur** [wildan3105/github-langs#154]
**Current behavior:**
When we have SCSS file changes we need to restart the server, and running again

**Expected behavior:**
When we have SCSS file changes, gulp file auto recompile the CSS

**Steps to reproduce:**
User gulp watch and add new script dev on package JSON

**Comment by urmauur** [comment]
@wildan3105 can you assign to me, I will work on it

**Comment by wildan3105** [comment]
sure go for it!

**Comment by wildan3105** [comment]
please fetch the latest master cause I've just re-structured a bit the repo @urmauur
