### ISSUE TITLE
Links on 404 not found page are not clear enough

### ISSUE THREAD

**Issue by wildan3105** [wildan3105/github-langs#155]
**Current behavior:**
Since we have a royal blue background and the links on the 404 page are also in blue (less dark), it's kind of hard to be aware of the links (back to home & issues link)

![404](https://user-images.githubusercontent.com/7030099/94910277-b5837f00-04ce-11eb-970e-7c2e55874e5a.png)

**Expected behavior:**
Use the custom color (more bright) with the same experience of click and redirection.

**Steps to reproduce:**
https://github-langs.herokuapp.com/randompage

**Comment by or-yam** [comment]
Can I take this one ?

**Comment by wildan3105** [comment]
sure go for it @or-yam !

**Comment by wildan3105** [comment]
please fetch the latest master cause I've just re-structured a bit the repo @or-yam

**Comment by or-yam** [comment]
how do i setup the process.env?
tried to create .env file in the root folder but got `Missing CLIENT_ID and CLIENT_SECRET environment variables`

**Comment by wildan3105** [comment]
From your terminal, you can just run it using this command:
`CLIENT_ID=your_client_id CLIENT_SECRET=your_client_secret ENV=local npm start`

**Comment by wildan3105** [comment]
Closed by #157
