### ISSUE TITLE
Add badge for organization account

### ISSUE THREAD

**Issue by wildan3105** [wildan3105/github-langs#16]
**Current behavior:**
We don't know if the user we search is usual user or organization. Based on the github API, the categorization is divided into `User` and `Organization`. Sample data follows : 
```json
{
...
  "type": "User",
...
}
```
And if the user we search is organization, the value of `type` is `Organization`.

**Expected behavior:**
From the above statement, I'd like to add feature to display a badge for organization. The badge could be displayed next to the user's avatar. And when we hover to that badge, it will show an organization's name

**Comment by ChrisMcNulty91** [comment]
Do you have an icon to use for the badge?

**Comment by wildan3105** [comment]
Hi @ChrisMcNulty91, you can see below image : 
![verified_badgy](https://user-images.githubusercontent.com/7030099/31382594-689a755e-ade2-11e7-80df-6c77da8d56e0.png)
Do you want to work on this?

**Comment by Xenira** [comment]
I could give it a try as well

**Comment by wildan3105** [comment]
Yeah please you guys could work on this and we'll discuss the result :) @ChrisMcNulty91 @Xenira

**Comment by ChrisMcNulty91** [comment]
@wildan3105 Yeah I can take a look at this

**Comment by ChrisMcNulty91** [comment]
Before I submit a PR what do you think of this? Should it be smaller? should we place it somewhere else on screen?

![language-checker](https://user-images.githubusercontent.com/3280158/31384703-f265bfd0-adb7-11e7-924b-d07a02442e33.PNG)

**Comment by wildan3105** [comment]
Nice! But, could you move the position of the badge to the bottom-right-corner like this one?

![badge copy](https://user-images.githubusercontent.com/7030099/31385027-bcd4c2f6-adeb-11e7-8dda-89f1d6e3af61.png)

And make sure when we `hover` to that badge, it will display the name of organization :ok_hand:

**Comment by wildan3105** [comment]
Closed by #20
