### ISSUE TITLE
[Help needed] add unit test for utils: chart.js

### ISSUE THREAD

**Issue by wildan3105** [wildan3105/github-langs#163]
**Current behavior:**
Not all utils are fully covered with unit test.

**Expected behavior:**
Every util should be covered by the unit test so we're confident with every change we make to that file. We can follow the unit test approach that I've made in this folder: https://github.com/wildan3105/github-langs/tree/master/tests/utils

**Steps to reproduce:**
File: https://github.com/wildan3105/github-langs/blob/master/lib/public/js/chart.js
Coverage:
![colors](https://user-images.githubusercontent.com/7030099/94982038-97b32a00-0561-11eb-8907-7d20098e301d.png)

**Comment by ashikvarma11** [comment]
@wildan3105  I would like to take this one. Could you assign me this?

**Comment by wildan3105** [comment]
yeah sure go ahead!

**Comment by wildan3105** [comment]
Please be mindful because `chart.js` is actually a collection of utils, so maybe you need to refactor a bit to make it more readable, easy to test, and easy to develop in the future :+1: 
Take your time to understand the code first before making any changes :ok_hand: @ashikvarma11

**Comment by ashikvarma11** [comment]
@wildan3105  I attempted to cover about 30% of the lines in Chart.js. But I need a few clarifications regarding this. For chart.js, spinner.js and other such files, testing  the functionality requires running it on the browser. Can we use something like Puppeteer or Cypress?

**Comment by wildan3105** [comment]
> @wildan3105  I attempted to cover about 30% of the lines in Chart.js. But I need a few clarifications regarding this. For chart.js, spinner.js and other such files, testing  the functionality requires running it on the browser. Can we use something like Puppeteer or Cypress?
> 
> 
> 
> I'm trying it with jsdom() for mocha. I'm not sure if it gives the required results.

Hmm I think for now the prioritization is at least have some coverage on each util. For chart.js, I believe you can make the unit test for `parse` and `sum` function. For the rest, as it requires running on the browser, we can create separate issues. What do you think @ashikvarma11 ?

**Comment by wildan3105** [comment]
Also please help me to confirm whether we still use this function: https://github.com/wildan3105/github-langs/blob/bfe4961d2258175e0e8b6923dccb57fa48bb7333/lib/public/js/chart.js#L4 :thinking: 

And also you can export those functions inside the `chart.js` so you can test it in the `/tests` folder

**Comment by ashikvarma11** [comment]
> > @wildan3105  I attempted to cover about 30% of the lines in Chart.js. But I need a few clarifications regarding this. For chart.js, spinner.js and other such files, testing  the functionality requires running it on the browser. Can we use something like Puppeteer or Cypress?
> > I'm trying it with jsdom() for mocha. I'm not sure if it gives the required results.
> 
> Hmm I think for now the prioritization is at least have some coverage on each util. For chart.js, I believe you can make the unit test for `parse` and `sum` function. For the rest, as it requires running on the browser, we can create separate issues. What do you think @ashikvarma11 ?

Good idea. I think we can have an open discussion about which tool to use.

**Comment by ashikvarma11** [comment]
> Also please help me to confirm whether we still use this function:
> 
> https://github.com/wildan3105/github-langs/blob/bfe4961d2258175e0e8b6923dccb57fa48bb7333/lib/public/js/chart.js#L4
> 
> 🤔
> And also you can export those functions inside the `chart.js` so you can test it in the `/tests` folder

No, we don't use it anywhere else. I guess, it was used earlier to parse the languages. I have written tests for it though. 😆

**Comment by wildan3105** [comment]
> > Also please help me to confirm whether we still use this function:
> > https://github.com/wildan3105/github-langs/blob/bfe4961d2258175e0e8b6923dccb57fa48bb7333/lib/public/js/chart.js#L4
> > 
> > thinking
> > And also you can export those functions inside the `chart.js` so you can test it in the `/tests` folder
> 
> No, we don't use it anywhere else. I guess, it was used earlier to parse the languages. I have written tests for it though. laughing

Haha LOL. You can delete that function tho. Sorry for the hussle. In exchange, I think you can test this function: 
https://github.com/wildan3105/github-langs/blob/bfe4961d2258175e0e8b6923dccb57fa48bb7333/lib/public/js/chart.js#L119
