### ISSUE TITLE
[Help needed] add unit test for util: spinner.js

### ISSUE THREAD

**Issue by wildan3105** [wildan3105/github-langs#165]
**Current behavior:**
Not all utils are fully covered with unit test.

**Expected behavior:**
Every util should be covered by the unit test so we're confident with every change we make to that file. We can follow the unit test approach that I've made in this folder: https://github.com/wildan3105/github-langs/tree/master/tests/utils

**Steps to reproduce:**
File: https://github.com/wildan3105/github-langs/blob/master/lib/public/js/spinner.js
Coverage:
![colors](https://user-images.githubusercontent.com/7030099/94982038-97b32a00-0561-11eb-8907-7d20098e301d.png)

**Note**
Still not sure if this specific util can be covered by unit test. Maybe we can refactor it first? Open for suggestion though

**Comment by arthur322** [comment]
Hello! Can I take this issue?

**Comment by wildan3105** [comment]
yes sure!
