### ISSUE TITLE
Hide layout chart when a user has no repo

### ISSUE THREAD

**Issue by wildan3105** [wildan3105/github-langs#18]
**Current behavior:**
For the user that has no repo, it display chart only with layout (no value) like this : 

![norepo](https://user-images.githubusercontent.com/7030099/31384053-83dbc048-ade7-11e7-9012-190d1b8f4ad4.png)

**Expected behavior:**
Get rid of that chart layout.

**Comment by shalithasuranga** [comment]
I like to work with this issue

**Comment by wildan3105** [comment]
Sure! @shalithasuranga. It's all yours. Mention me if you need anything :ok_hand:

**Comment by metamaker** [comment]
:(  I already modified code for it, just was doing some cleaning up. @shalithasuranga  may you pick something different?

**Comment by wildan3105** [comment]
Do you guys want to share the screenshot of your update please? @shalithasuranga @metamaker

**Comment by metamaker** [comment]
> Do you guys want to share the screenshot of your update please? @shalithasuranga @metamaker
@wildan3105 ok

**Comment by wildan3105** [comment]
**UPDATE** It would be a way better if we could make an object like this : 
```javascript
show = {
result:none,
chart:none,
emoji:none
}
```
And based on #17, we should ignore the `showLanguage` because it's not relevant (replaced by chart.js)

**Comment by metamaker** [comment]
![screen shot 2017-10-10 at 15 13 03](https://user-images.githubusercontent.com/5102404/31388206-9536eabc-adcd-11e7-97d7-118ba7d7699d.png)

**Comment by shalithasuranga** [comment]
Hi..

Okay no worries @metamaker 

@wildan3105  Here is the screenshot 

![image](https://user-images.githubusercontent.com/18402702/31388192-e1763fbe-adea-11e7-996b-c59ae0ad4463.png)

I used `<div style="display:{{showChart}}" id="canvas-container"` similar to existing things

**Comment by metamaker** [comment]
https://github.com/metamaker/github-langs/commit/62e6f758cad92640248f87fdbed484f85bb25b51

But I want to clean it up a bit more before making PR. You have callbacks hell here (http://callbackhell.com/).

**Comment by shalithasuranga** [comment]
Here what I modified https://github.com/wildan3105/github-langs/compare/master...shalithasuranga:norepoissue?expand=1

**Comment by metamaker** [comment]
Yep, it was displayed above :)

**Comment by wildan3105** [comment]
Thanks everyone ! 
Does anybody want to implement my suggestion below ? 

> show = {
result:none,
chart:none,
emoji:none
}

@metamaker I'm aware of the callbackhell. You could submit an issue an propose a solution if you have one :)

**Comment by metamaker** [comment]
> Does anybody want to implement my suggestion below ?
will do

> You could submit an issue an propose a solution if you have one :)
You use babel, so you have async/await combo. I can refactor it pretty quickly.

**Comment by wildan3105** [comment]
@metamaker If you don't mind, you could refactor it using async/await or promise and submit a PR about it. I will wait!

**Comment by wildan3105** [comment]
Thank you guys :) @shalithasuranga @metamaker. Closed by #21 

@shalithasuranga If you want to contribute at anything, feel free to open an issue :)
