### ISSUE TITLE
Add vertical graph that dinamically display programming language based on user's repos

### ISSUE THREAD

**Issue by wildan3105** [wildan3105/github-langs#2]
**Current behavior:**
Currently, programming language(s) from user's repo only displayed as text, each with the amount of the repo(s). Output that passed from `controllers` are an object which consist of programming language and its amount, e.g : 
```javascript
{"javascript":30, "HTML":20, "go":10}
```

**Expected behavior:**
This feature will show vertical graph that dinamically display programming language based on repo. We can use library like [d3.js](https://d3js.org/) or [chart.js](http://www.chartjs.org/) or even Google Chart. Any libraries welcome as long as the output follow the image below : 

![graph](https://user-images.githubusercontent.com/7030099/31350556-dbd02faa-ad51-11e7-9687-75869164affd.png)

**Comment by juancuiule** [comment]
I can work on this

**Comment by wildan3105** [comment]
That's cool! @juancuiule just mention me if you need anything more clear :ok_hand:

**Comment by juancuiule** [comment]
Hi @wildan3105 I created a function that takes that languages object and creates the Chart, the issue that I'm having is that I have to call that function with the languages variable that handlebars receives. Do you know if there is a way to do that? Something like {{ createChart(languages) }}
being `createChart` defined inside an script tag and languages a value that comes from the server.

**Comment by wildan3105** [comment]
Hi, thank you for reaching me out. So, if I don't get it wrong, you need to call the function passed from server to run in `script` tag at handlebars, is that right? What library do you use for displaying chart?
Honestly, I'm a still a newbie on handlebars thing so I still have no idea about this.

**Comment by juancuiule** [comment]
```javascript
const chart = (languages) => new Chart(document.getElementById('myChart'), {
      type: 'bar',
      data: {
        labels: Object.keys(languages),
        datasets: [{
          label: "Language Stats",
          backgroundColor: 'rgb(255, 99, 132)',
          borderColor: 'rgb(255, 99, 132)',
          data: Object.values(languages),
        }]
      },
      options: {
        scales: {
          yAxes: [{
            ticks: {
              beginAtZero: true
            }
          }]
        }
      }
    });
```

I have that function in `main.handlebars` the issue is that I have to run it with the data that comes from the server (something like chart(languages)) and I don't know how to use it inside the script tag where that function is defined

**Comment by wildan3105** [comment]
Okay I'll look into it when I have a longer time, keep up the good work @juancuiule !

**Comment by juancuiule** [comment]
I found a way to parse that data, I'll be making a PR in a minute
