### ISSUE TITLE
Avoid callback hell / refactor the controllers

### ISSUE THREAD

**Issue by metamaker** [wildan3105/github-langs#22]
**Current behavior:**
It is impossible to use all ES2017 features for this project at the moment. For example, it is impossible to use async/await combo (https://hackernoon.com/6-reasons-why-javascripts-async-await-blows-promises-away-tutorial-c7ec10518dd9) to deal with callback hell problem in `controller.js`.

**Expected behavior:**
As developer, I want to develop project in most efficient and bug-free way. Some of ES2017 features boost productivity significantly.

The easiest solution would be moving project to some already existing and well configured boilerplate for Node.JS Express + Babel, e.g. https://github.com/vmasto/express-babel. Other way is to require Node.JS >= 7.6, which has async/await, for this project (which is not perfect in my eyes, bcz right now I am able to run project in Node.JS 7.3 without problems).

**Comment by Xenira** [comment]
What about typescript and setting the target to whatever ES version you need?

**Comment by metamaker** [comment]
I am not maintainer, just proposing useful change.

> What about typescript and setting the target to whatever ES version you need?

Typescript is also good, but JS only a subset of it. Babel-compliant code is real Javascript. So both will work, but from my experience with TypeScript and Babel, I would recommend Babel. It is less buggy and confusing.

**Comment by Xenira** [comment]
Sadly I have no experience with Babel. Max I could do is TS.

**Comment by wildan3105** [comment]
Sorry for the late reply. Actually, this project was inspired by [hacktoberfest-checker](https://github.com/jenkoian/hacktoberfest-checker). So, if you look at the project structure, it's not much different. At the beginning, I tried to use `axios` as promise-based HTTP calls library, but somehow I can't get it done. So, before use Babel (which I'm not familiar with), could we use promised-based HTTP calls library (axios, bluebird)? 

Suggestions are welcome :)

**Comment by metamaker** [comment]
I am working on https://github.com/wildan3105/github-langs/issues/23, hope that somebody else can help with this issue. As about axios/bluebird support, I used both and they are both good, so adding any of them will be okay.

**Comment by wildan3105** [comment]
Alright :ok_hand: @metamaker

**Comment by uLan08** [comment]
I am able to run the project on node 8.4.0. The Docker base image I created for this project is on node 8.5

**Comment by wildan3105** [comment]
What do you mean @uLan08 ? Is your statement related to this issue?

**Comment by uLan08** [comment]
Ah yes, since @metamaker was also suggesting to require Node.js >= 7.6 and so I was giving feedback that so far it works with latest versions of Node. With that we could skip babel and just require a certain version of Node for `async/await` to work.

**Comment by metamaker** [comment]
There is no problem with running project on Node >= 7.3, the problem would be running it on Node <= 7.6 if I changed callbacks to async/await. But you are right, if we have docker image, it is now easier to rely on anything that we need.

**Comment by uLan08** [comment]
Yes, then it just needs to be decided on which path to choose. Require Node versions >= 7.6 or add babel to the project.

**Comment by wildan3105** [comment]
I would open to either options, as long as it solve issue.

**Comment by metamaker** [comment]
Let's pick NodeJS >= 7.6 path, because it is as easy as single apt-get command atm. Babel path requires more work. Also I see that we already have node 8.5 in docker, so let's stick with it.

**Comment by juancuiule** [comment]
Hey! Who is working in this?

**Comment by wildan3105** [comment]
Up to you guys @metamaker @Xenira @juancuiule ! But this issue is **urgent** and **strategic**, so it will be a burden to another issue(s) unless this issue is fixed first. Thank yo :)

**Comment by juancuiule** [comment]
I'll try to help with this, probably using async/await

**Comment by wildan3105** [comment]
Solved elegantly by @juancuiule in #46 !
