### ISSUE TITLE
Add screenshot testing

### ISSUE THREAD

**Issue by metamaker** [wildan3105/github-langs#23]
**Current behavior:**
It is nearly impossible to test this application by using conventional tools, because it is 95% GUI, so there are no tests at all. There is such tool as https://github.com/Huddle/PhantomCSS that could be used for screenshot testing, which will help make this project stable.

**Expected behavior:**
It would be easy to check screenshots for anomalies (e.g. missing labels or wrong text), if screenshot testing process was included in `npm run test`.

**Comment by wildan3105** [comment]
Thanks for the issue. Could you elaborate more about the screenshot testing? What objects to be tested, what result expected?

**Comment by metamaker** [comment]
@wildan3105 If you check https://github.com/wildan3105/github-langs/pull/17, you will see that benjaminr177 wrote "Oh, my bad - forgot to test on main page.". If you had screenshot testing, you would expect that new screenshot of homepage would be the same as old screenshot, and this would prevent an issue with homepage immediately.

Screenshots are tested against other screenshots on pixel by pixel basis. Also you will be able to immediately see on screenshots how all your application's screens look like, so you will be able to check if screenshots are really looking good or not before pushing to master. This is not replacement for unit/integration/e2e testing (whatever, this is small funny project, you don't need most of this stuff),  but another way to make easier verification that app works correctly.

There are also other opportunities, e.g. Jest from Facebook that can be used for snapshot (_not screenshot!_) testing, i.e. it checks only DOM changes.

**Comment by metamaker** [comment]
`npm run test` doesn't do any testing at the moment. Linting is just validation for syntax errors. It should be done by every good IDE on fly, so command is no use at the moment.

**Comment by wildan3105** [comment]
Okay, I got your point. You could work on this, create a PR, and we can see the results. Please make a list (checklist at this issue / your coming up PR) of cases to be tested and check it if you succeed. I'm very appreciate with your help :+1: 

One last thing, should we add `test` at the `root` project for this case?

**Comment by metamaker** [comment]
> Please make a list (checklist at this issue / your coming up PR) of cases to be tested and check it if you succeed.

I will add list here a bit later :+1: 

> One last thing, should we add test at the root project for this case?

Yes, I will create `/tests` folder in PR, because there must be JS file with test suite.

**Comment by wildan3105** [comment]
Okay, it's all yours then @metamaker !

**Comment by metamaker** [comment]
[ ] Homepage
[ ] Profile page (with username of non existing user)
[ ] Profile page (with username of user who has 0 repos)
[ ] Profile page (with username of user who has >0 repos)

This should cover 95% of cases. I don't see much sense in testing `Profile page (with username of user who has >0 repos)` when user has 9 repos, 19 repos, etc. at the moment (i.e. on emoji breaking points), because used JS code will be the same for all these cases.

**Comment by wildan3105** [comment]
Thanks ! @metamaker Closed by #52
