### ISSUE TITLE
Run the app within Docker

### ISSUE THREAD

**Issue by wildan3105** [wildan3105/github-langs#25]
**Current behavior:**
As you know, this app (so far) could be run only with the npm.

**Expected behavior:**
Since containerization is a trend now, an alternative to run the app within Docker is really good. So, feel free to configure this app to run within Docker and update the `README.md` based on that.

**Comment by uLan08** [comment]
I'll work on this :whale:

**Comment by wildan3105** [comment]
Okay, go on! @uLan08

**Comment by wildan3105** [comment]
Closed by #26
