### ISSUE TITLE
Fix footer position

### ISSUE THREAD

**Issue by wildan3105** [wildan3105/github-langs#28]
**Current behavior:**
When homepage rendered, the footer position is good, like this : 
![current0](https://user-images.githubusercontent.com/7030099/31443092-a3c0cc6a-aec2-11e7-8dd5-d4a47de857db.png)

But when search is done, the footer covered the chart horizontal axis title like this : 

![current2](https://user-images.githubusercontent.com/7030099/31443127-be25a9b8-aec2-11e7-9e1c-60a872e4f724.png)

**Expected behavior:**
Footer would not cover the chart horizontal-axis title and always displayed below of that title.

**Comment by ccalamos** [comment]
I can work on this
