### ISSUE TITLE
Display more than 100 repos

### ISSUE THREAD

**Issue by wildan3105** [wildan3105/github-langs#3]
**Current behavior:**
Based on the API call : `https://api.github.com/users/${username}/repos?client_id=${client_id}&client_secret=${client_secret}&per_page=100`, it only display 100 repos on a single page. User that has more than 100 repo will not be able to get the actual result. To do so, it should add parameter `page=2` and so on (`page=3..`) until the result of the `nth` page is less than `100` to the API call.

**Expected behavior:**
Display the actual amount of user's repo, regarding how many repos he/she may has.

**Comment by Leocardoso94** [comment]
I will work on this

**Comment by wildan3105** [comment]
Okay @Leocardoso94, it's all yours ! Feel free to mention me if you need anything :ok_hand:

**Comment by Leocardoso94** [comment]
@wildan3105 Do you know any user that has more than 100 repos?

**Comment by wildan3105** [comment]
@Leocardoso94 some friends of mine like [at]sonnylazuardi

**Comment by wildan3105** [comment]
Closed by [#4](https://github.com/wildan3105/github-langs/pull/4)
