### ISSUE TITLE
[UI] Some language names are not showing in the chart

### ISSUE THREAD

**Issue by IOAyman** [wildan3105/github-langs#33]
**Current behavior:**
Some language names are not showing under their respective bars in the chart.  
However, when I hover on the bars, the tooltip show the language name normally.

**Expected behavior:**
They should be displayed below the bars as well.

![screenshot-2017-10-11 github language checker](https://user-images.githubusercontent.com/6185849/31450313-67fa24ce-aea9-11e7-848e-e8b5d33fd3be.png)

**Comment by wildan3105** [comment]
I'm aware of this. I thought this bug was from `chart.js`? Let's discuss it here

**Comment by wildan3105** [comment]
Found an issue about it [chartjs](https://github.com/chartjs/Chart.js/issues/2801)

**Comment by juancuiule** [comment]
@wildan3105 when I added the chart I realized that this was happening and made some css rules in order to make the graph responsive, we could try by showing the language tag when the bar is `:hover`. I can take a look at this later today, but if @IOAyman wants to take it that's :+1:

**Comment by IOAyman** [comment]
@juancuiule, Please do, I don't mind at all 😉 

Thank you :)

**Comment by juancuiule** [comment]
Google screenshot:
![screenshot from 2017-10-11 16 27 34](https://user-images.githubusercontent.com/12143451/31461976-705f011e-aea1-11e7-9829-2c8973445291.png)

Regular Human screenshot:
![screenshot from 2017-10-11 16 27 49](https://user-images.githubusercontent.com/12143451/31461977-708b0336-aea1-11e7-867c-ca6641d835e3.png)

I found that we could rotate the xAxis labels 90° an they will fit if we make the graph almost 100% width which does not look good with a few languages... we can add something to change this in execution time analyzing the number of languages that the user has.

@IOAyman @wildan3105 any feedback?

**Comment by wildan3105** [comment]
I think we should limit the display of chart when a user has more than `n` repo language to fit the screen. My thought is the screen should remain constant, and the width must not exceed too far from the width of `search bar`.

**Comment by juancuiule** [comment]
how many languages are you thinking?

**Comment by wildan3105** [comment]
As long as it not exceed the `screen bar`'s width too much, that would be okay. I could see that `chart.js` has a relative size for single vertical bar based on the data length, right? Maybe we could do trial-error (with different user's repo amount) to count how many languages are best to display.

**Comment by juancuiule** [comment]
I think that 20 is a good number, and I think that we could add a few features in order to allow the user to see more than 20, or just to sum every other language in a bar that says "Others"

**Comment by wildan3105** [comment]
Closed by #41
