### ISSUE TITLE
Improve the 404 page design

### ISSUE THREAD

**Issue by IOAyman** [wildan3105/github-langs#36]
**Current behavior:**
The current 404 page looks ugly. Really ugly!

**Expected behavior:**
If somebody takes the time to make it look better, that would be appreciated 😄

**Comment by wildan3105** [comment]
Screenshot of current 404 page : 

![404](https://user-images.githubusercontent.com/7030099/31485478-2fdad8ee-af5e-11e7-9348-348dda1b8a76.JPG)

Anyone who'd like to contribute might consider this checklist : 

- [ ]  Make the text all `white` and more center (move it down)
- [ ] Add `back to homepage` link
- [ ] Add footer

**Comment by slavabez** [comment]
I'm on it

**Comment by wildan3105** [comment]
Add 404 image like this [404](https://www.google.co.id/search?biw=1235&bih=686&tbm=isch&sa=1&btnG=Search&q=404+image) would be good too :+1:

**Comment by wildan3105** [comment]
Closed by #42
