### ISSUE TITLE
Make the chart clickable

### ISSUE THREAD

**Issue by IOAyman** [wildan3105/github-langs#39]
**Current behavior:**
Currently, hovering over bars in the chart shows a tooltip with the name of the corresponding language and the number of its repos.

**Suggested behavior:**
Can we make the bars clickable?  Whenever a bar is clicked it opens up the user's profile filtering only the repos for that specific language.

For instance, if I click on the JavaScript bar in my [profile] I would be redirected to my profile filtering only the JavaScript [repos] I have.

The URL structure should be something like this:
```js
`https://github.com/${username}?tab=repositories&type=&language=${language}`
```

[profile]: https://githublangs.herokuapp.com/?username=ioayman
[repos]: https://github.com/IOAyman?tab=repositories&type=&language=javascript

**Comment by wildan3105** [comment]
That would be good :+1: But consider todo list I just updated at `README.md` :smile: and check the 7th point :ok_hand:
