### ISSUE TITLE
Double avatar and problem on hover vertical bar with user's language > 20

### ISSUE THREAD

**Issue by wildan3105** [wildan3105/github-langs#40]
**Current behavior:**
![bug](https://user-images.githubusercontent.com/7030099/31489721-cedad680-af6b-11e7-9633-b602a8d55595.JPG)

**Expected behavior:**
Only show single avatar and better handling on hover vertical bar of user that has more languages > 20, move the footer position back at the bottom-center and title page didn't work

**Comment by juancuiule** [comment]
This may have something to do with previous merges from other issues...

**Comment by wildan3105** [comment]
Okay I'll check it first. Sorry @juancuiule

**Comment by juancuiule** [comment]
I know why this is happening...

**Comment by wildan3105** [comment]
Hi @juancuiule, I already solved! I revert just before merge PR about #35
Will push ASAP

**Comment by wildan3105** [comment]
I was fixing the problem until I thought your solution was better so I just merged it :smile: :+1: @juancuiule 
Thank you so much for all the PRs! Maybe you'd like to be an active contributors for this project :wink:

**Comment by wildan3105** [comment]
Closed by #41
