### ISSUE TITLE
Modify search result 

### ISSUE THREAD

**Issue by wildan3105** [wildan3105/github-langs#43]
**Current behavior:**
Results are shown like this : 
![current2](https://user-images.githubusercontent.com/7030099/31496193-913e572a-af84-11e7-82bf-0ffc471be5c3.png)

**Expected behavior:**
It would be good to show the amount of unique language(s) accross repo(s) of github's account. I made a simple sketch of it : 

![new](https://user-images.githubusercontent.com/7030099/31496256-ea24597a-af84-11e7-8a9b-76b6118a149a.png)

I think it's more clean and informative. Or maybe we could add the icon of `repo` and `language` (?) Suggestions are welcome.

**Comment by lakk1** [comment]
I will work on it

**Comment by wildan3105** [comment]
Hi @lakk1, are you still working on this? Please tell me if you need anything :ok_hand:

**Comment by lakk1** [comment]
Yes @wildan3105 I am

**Comment by lakk1** [comment]
I can't push changes to repo @wildan3105

**Comment by wildan3105** [comment]
Sorry @lakk1, since so many PRs were merged, you should `pull` it first or `git rebase`

**Comment by lakk1** [comment]
@wildan3105  I have done rebase but still facing error : 403

**Comment by wildan3105** [comment]
I thought you only edited the `views/layout/main.handlebars`, right? So right now you must edit the `views/partials/body.handlebars` since previous PRs re-structure the `views` directory

**Comment by wildan3105** [comment]
And right now we use `axios` as promised-based HTTP call

**Comment by lakk1** [comment]
I have edited `views/partials/body.handlebars` and `views/partials/body.handlebars`

**Comment by wildan3105** [comment]
You should make a PR so I could give you a help/hint about the problem

**Comment by wildan3105** [comment]
Are you still working on this or not? @lakk1 If not, I'll solve this problem by myself. Thank you

**Comment by lakk1** [comment]
Sorry,  @wildan3105 I was busy in other work I am not working on it.

**Comment by wildan3105** [comment]
:ok_hand: @lakk1
