### ISSUE TITLE
Mobile responsive 

### ISSUE THREAD

**Issue by wildan3105** [wildan3105/github-langs#44]
**Current behavior:**
Some elements were overlapped if accessed from a smartphone, picture below : 

![mobile](https://user-images.githubusercontent.com/7030099/31509198-dff20de6-afaa-11e7-8139-8c5dbabb605b.jpg)

**Expected behavior:**
**Fork me** button should not overlap with the header, and footer displayed full

**Comment by Trommelochse** [comment]
can take that

**Comment by wildan3105** [comment]
Go on @Trommelochse !

**Comment by udithishara** [comment]
aw, Sorry @Trommelochse i didn't see your comment when i pulled 😕

**Comment by wildan3105** [comment]
Hi guys @Trommelochse @udithishara, thanks for the quick responses! I'll see the result of yours first, particularly will wait the PR from @Trommelochse :)

**Comment by wildan3105** [comment]
Solved by @udithishara

**Comment by wildan3105** [comment]
Reopen because badge position not responsive when accessed via mobile : 

![badge](https://user-images.githubusercontent.com/7030099/31574067-ae0d6e86-b0f1-11e7-8427-c62b79f0cce3.png)

**Comment by masquel** [comment]
@wildan3105 also footer should be fixed and add some space from bottom to see content that under footer

![image](https://user-images.githubusercontent.com/6623392/31588277-32587350-b1f8-11e7-962f-2b927f205a6c.png)

**Comment by wildan3105** [comment]
Okay @masquel, maybe mobile responsive improvement will be the last step after all the buttons are applied.

**Comment by wildan3105** [comment]
Closed because this issue is no longer relevant.
