### ISSUE TITLE
Add social share (twitter and facebook)

### ISSUE THREAD

**Issue by wildan3105** [wildan3105/github-langs#48]
**Current behavior:**
There is no external action after user knew their language statistics. 

**Expected behavior:**
User could share their language statistics result through facebook and twitter.

**Steps to reproduce:**
Make a new js file, placed in `lib/public/js` and add share and tweet button in `views/partials/body`.

**Comment by sandipmavani** [comment]
what information share 
such as link or graph snapshot
on twitter or facebook

**Comment by wildan3105** [comment]
Link to the result page, e.g : [here](https://githublangs.herokuapp.com/?username=sandipmavani)
And the information is the message shown in the result page, like : 'Keep going on JavaScript'
Both applied on twitter and facebook. Do you get that @sandipmavani ?

**Comment by uLan08** [comment]
@wildan3105 I was working on this before this issue was posted. I have added a PR #49

**Comment by wildan3105** [comment]
Let us see both result of you guys @sandipmavani @uLan08 :)

**Comment by wildan3105** [comment]
Closed by #49
