### ISSUE TITLE
Special behavior on `null` programming language

### ISSUE THREAD

**Issue by wildan3105** [wildan3105/github-langs#5]
**Current behavior:**
Currently, github API only provide `null` value from an unknown language of repository. It's not fancy at all to display. 

**Expected behavior:**
Change `null` to `unknown` and make special behavior on `statement` if `null` language has the highest value like : 'Wow, you are a mystery man!', 'Wow, you like the mystery language', etc.

For the statement code, please take a look into this : [statement](https://github.com/wildan3105/github-langs/blob/master/lib/controller.js#L125-L132)

**Comment by juancuiule** [comment]
I can take a look at this one too

**Comment by wildan3105** [comment]
Closed by #8
