### ISSUE TITLE
Fix badge position, modify search result, and css issue(s)

### ISSUE THREAD

**Issue by wildan3105** [wildan3105/github-langs#58]
**Current behavior:**
Related to this [#43](https://github.com/wildan3105/github-langs/issues/43), also please change the position of badge of organization's account, because the current conditions is : 

![badge](https://user-images.githubusercontent.com/7030099/31572683-956144f0-b0d5-11e7-9bcc-95f386419868.png)

**Expected behavior:**
The expected result of badge position is : 

![badge copy](https://user-images.githubusercontent.com/7030099/31572684-a107f8bc-b0d5-11e7-8e7f-da23f6a9f99c.png)

And modify result become like this : 

![result](https://user-images.githubusercontent.com/7030099/31572687-b67c1386-b0d5-11e7-8fa4-6e00e8a6af40.png)

And tidy up the `lib/public/screen.css` because it's little bit messy. Any help would be much appreciated! 

P.S : **Please comment below if you would like to solve this issue so others don't unintentionally spend time on fixing something that may not end up getting merged**. Thanks!

**Comment by sagarvd01** [comment]
I'll take a look at it

**Comment by WarEnek** [comment]
Pls check badge position.

**Comment by wildan3105** [comment]
UPDATE : Badge position already solved by @WarEnek, the rest is yours @sagarvd01 :+1:

**Comment by wildan3105** [comment]
Are you still working on this ? @sagarvd01

**Comment by sagarvd01** [comment]
I saw a merged on this issue so I moved on already. I didn't saw your previous comment either
