### ISSUE TITLE
Toggle vertical bar graph color

### ISSUE THREAD

**Issue by wildan3105** [wildan3105/github-langs#60]
**Current behavior:**
Currently, the graph shown with a single color like this : 

![color](https://user-images.githubusercontent.com/7030099/31574608-6fca0286-b0fd-11e7-9b30-82e768904102.JPG)

**Expected behavior:**
A `toggle button` positioned next to graph would be nice to switch the vertical bar color from white to colorful based on language. I still have no idea how to put color for each language because github **does not provide** API for language color. Maybe create a `json` file contains `language-name` and `associated-color`? Or use existing repo like [github-color](https://github.com/ozh/github-colors). Any suggestions are welcome :)

This is also related to pull [#55](https://github.com/wildan3105/github-langs/pull/55) and [#54](https://github.com/wildan3105/github-langs/pull/54)

P.S : **Please comment below if you would like to solve this issue so others don't unintentionally spend time on fixing something that may not end up getting merged.** Thanks!

**Comment by iamham** [comment]
Let me help 💃

**Comment by wildan3105** [comment]
Hi @iamham, thanks for the work! But sometimes when I hover to the `single bar`, eventually the all bar changed to `white`, any idea about this?

**Comment by iamham** [comment]
yeah just saw that, please see #62 for the fix :D @wildan3105

**Comment by wildan3105** [comment]
Perfect fix! @iamham :+1: Thank you so much :100:
