### ISSUE TITLE
Beautify toggle color button 

### ISSUE THREAD

**Issue by wildan3105** [wildan3105/github-langs#64]
**Current behavior:**
This is the latest view if we search for username's repo : 

![screenshot4](https://user-images.githubusercontent.com/7030099/31577862-4f4d8c42-b140-11e7-8900-e319a468ee5f.png)

**Expected behavior:**
Like a normally switch `button`, it should show the condition like ON/OFF. So it would be better to change the style of the `button` and when it pressed, it will change the text (default is COLORFUL) so either the text is COLORFUL/WHITE. The reference style is attached below : 

![b1](https://user-images.githubusercontent.com/7030099/31577895-bef871f6-b140-11e7-96b3-4d2749b5d3a9.jpeg)
![n2](https://user-images.githubusercontent.com/7030099/31577901-ca8689cc-b140-11e7-9f7d-b4948649fe65.png)

Bootstrap useful link about toggle button : [bootstrap toggle button](http://www.bootstraptoggle.com/)

P.S : **Please comment below if you would like to solve this issue so others don't unintentionally spend time on fixing something that may not end up getting merged**.  Thanks!

**Comment by jakezaleski** [comment]
I'd love to help! Would you please clarify exactly what you want?

**Comment by wildan3105** [comment]
I want the existing `toggle button` to be the ones in **expected behavior** issue above. So when it pressed, it would change the text in the button to `WHITE` and when it's not pressed, change the text to `COLORFUL`, do you get that? @jakezaleski

**Comment by roh777** [comment]
I understand your problem but this would require some changes to your chart.js file too. How do we know that button is in clicked(colored) state vs inactive(white) stage.

I think a boolean colored variable will help, in your case it's SingleColor variable. Using it we can change the background of the button for different states.

Should I work on this approach? Or do you want to do this some other way?

**Comment by wildan3105** [comment]
I know your point @roh777. A boolean toggle then would be good too :+1: You could work on this and see what solution from @jakezaleski :)

**Comment by jakezaleski** [comment]
What about a simple if and else if statement? Something like [this](https://stackoverflow.com/questions/15400421/change-button-text-after-click-then-change-it-back-after-clicking-again)?

**Comment by jakezaleski** [comment]
Actually, I think @roh777 's solution works well. He wins :)

**Comment by wildan3105** [comment]
Okay @jakezaleski :) Thanks

**Comment by wildan3105** [comment]
Closed by #68
