### ISSUE TITLE
Error on hover unknown bar

### ISSUE THREAD

**Issue by masquel** [wildan3105/github-langs#66]
**Current behavior:**
Hover over `unknown` bar throws error

**Expected behavior:**
Show stats for unknown languages

**Steps to reproduce:**

1. Visit https://githublangs.herokuapp.com/?username=masquel  
2. hover over `unknown` chart bar 
3. open console. There will be error.

```
Chart.bundle.min.js:10 Uncaught TypeError: Cannot read property 'r' of null 
at new r (https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.0/Chart.bundle.min.js:10:3924)
```

**Comment by wildan3105** [comment]
Hi, thanks for open the issue @masquel ! Do you want to solve it by yourself or just let me do it? If you want it, I could give a `hacktoberfest` label anyway :+1: :smile:

**Comment by masquel** [comment]
@wildan3105 ok, I will try to find out what causes this problem.

**Comment by wildan3105** [comment]
Okay @masquel :ok_hand:

**Comment by masquel** [comment]
@wildan3105 this was because of null color. Now when you click on `unknown` bar, github will show all languages because of there is no 'other' or smth like this in guthub languages list
