### ISSUE TITLE
Beautify the buttons

### ISSUE THREAD

**Issue by wildan3105** [wildan3105/github-langs#68]
**Current behavior:**
Because of many PRs merged but style not concerned, the buttons look like not fancy like this : 

![buttons](https://user-images.githubusercontent.com/7030099/31581272-d01412f0-b191-11e7-8d9a-8e1f9c11d77e.JPG)

**Expected behavior:**
Make button `toggle` and `save` side by side, adding an icon for each button with standard `bootstrap` would be good :) Make sure the elements won't overlap (buttons and caption, e.g check with account like `google` and see what happen) Any helps will be much appreciated !

P.S : **Please comment below if you would like to solve this issue so others don't unintentionally spend time on fixing something that may not end up getting merged. Thanks!**

**Comment by rowhitswami** [comment]
I'd like to take this one :blush:

**Comment by wildan3105** [comment]
Please make sure you test with every use case ! 
- [ ] user not found
- [ ] user has no repo
- [ ] user has several repos
- [ ] user is an organization

Thanks!

**Comment by wildan3105** [comment]
@rowhitswami please refer to the latest `master branch` since previous PR has been merged a few seconds ago :+1:

**Comment by roh777** [comment]
I would like to give this one a try! Alright?

**Comment by wildan3105** [comment]
Alright, give it a shot @roh77!

**Comment by wildan3105** [comment]
@roh777 I mean, sorry I access github via mobile right now :smile:

**Comment by wildan3105** [comment]
Closed by #69
