### ISSUE TITLE
Update process.env variables

### ISSUE THREAD

**Issue by juancuiule** [wildan3105/github-langs#7]
**Current behavior:**
The readme says that you should have a .env file with something like this
```
CLIENT_ID=your_client_id
CLIENT_SECRET=your_client_secret
```
but in `/lib/controllers.js` the code says
```javascript
const client_id = process.env.client_id;
const client_secret = process.env.client_secret;
```

**Expected behavior:**
Should be all caps or lower case in order to match

**Comment by wildan3105** [comment]
Ah I missed that one, nice detail!

**Comment by wildan3105** [comment]
Solved by [update .env vars to uppercase](https://github.com/wildan3105/github-langs/commit/761bc222cc007a3d690da54504b0a66a8bb7cba3)
