### ISSUE TITLE
Save chart as in image is without file name

### ISSUE THREAD

**Issue by Leocardoso94** [wildan3105/github-langs#70]
**Current behavior:**

Saving the chart as an image is without a filename and an extension
![image](https://user-images.githubusercontent.com/12713314/31628979-ff692342-b290-11e7-87ae-a6627c7c6a7b.png)

**Expected behavior:**
A file with the extension .jpg

**Steps to reproduce:**

Search some user and save image

Fixed it in #71

**Comment by wildan3105** [comment]
Closed by #71
