### ISSUE TITLE
Getting error message when Toggle color of Chart

### ISSUE THREAD

**Issue by Leocardoso94** [wildan3105/github-langs#72]
**Current behavior:**
Getting error message when Toggle color of Chart
![gif](https://user-images.githubusercontent.com/12713314/31630303-fa86838e-b294-11e7-9270-6eb0e2f755cb.gif)

**Expected behavior:**
No error message

**Steps to reproduce:**
Toggle color of the chart

Fixed it in #71

**Comment by wildan3105** [comment]
Hi @Leocardoso94 thanks for the issue(s) and PRs! I'll review it first :+1:

**Comment by wildan3105** [comment]
Closed by #71
