### ISSUE TITLE
Improve UI (any improvements welcome!)

### ISSUE THREAD

**Issue by wildan3105** [wildan3105/github-langs#73]
**Current behavior:**
So far it's quite good for a search-based website. The results shown in a graph, then could be saved in a `jpeg` file.

![screenshot5](https://user-images.githubusercontent.com/7030099/31719523-f567b558-b43d-11e7-8d1b-999cf2c551a2.png)

**Expected behavior:**
But the research is never done. Any improvements welcome ! Let's discuss here first to see what would be the next UI improvement for this site.

**Comment by acolombo25** [comment]
Use a nicer color palette for graph bars. An example could be found here: [material-design](https://material.io/guidelines/style/color.html#color-color-palette), but there are many others ones,

**Comment by wildan3105** [comment]
Hmm that one would be good too :+1: @acolombo25. But could you suggest another improvement?

**Comment by roh777** [comment]
There is still problem with the verified badge, the profile image shrinks in size, but the blue tick badge remains the same for smaller screen sizes or on mobile.

**Comment by wildan3105** [comment]
Yes I'm aware of that @roh777, could you resolve that? :smile:

**Comment by roh777** [comment]
I will look it up to see if I can do this.

**Comment by Klubiniecki** [comment]
Hey @wildan3105 !
I like clean, minimalist design. Will give it a go, let's see if you like my re-design :)
Loving the project btw.
Cheers!

**Comment by wildan3105** [comment]
Hi @Klubiniecki, thanks for the reply! I'd like to apply your change, but maybe we could `switch` theme instead replace the old one? Wait for your PR :+1:

**Comment by Klubiniecki** [comment]
Thanks for a quick answer @wildan3105, you mean adding a "switch theme" button? :)

**Comment by wildan3105** [comment]
Yes, that's right @Klubiniecki

**Comment by Klubiniecki** [comment]
Perfect, let me see how to go about it and maybe will make it a few PR's even 👌

**Comment by Klubiniecki** [comment]
@wildan3105 I fired you an email, let me know what you think ✉️
