### ISSUE TITLE
Convert some js file to use ES6 standards

### ISSUE THREAD

**Issue by wildan3105** [wildan3105/github-langs#76]
**Current behavior:**
There are many `js` file in this project. The ones that follow the ES6 standards and `eslint` are in the `lib` directory (`app.js` and `controller.js`), but some files in `lib/public/js` are not following those rules.

**Expected behavior:**
Convert the code style in `lib/public/js` directory to use ES6 standards and test it with `eslint` style which defined in `.eslintrc.json` without reduce any functionality of those codes (make the code run faster if you could!)

**Comment by kennyhuynh125** [comment]
I can try and handle this!

**Comment by wildan3105** [comment]
Closed by #79
