### ISSUE TITLE
UI - Dark theme re-design

### ISSUE THREAD

**Issue by klubiniecki** [wildan3105/github-langs#80]
**Current behavior:**
Site looks great, but as always some UI improvements can be done.

**Expected behavior:**
Clean, functional UI.

**Comment by wildan3105** [comment]
Thanks! @Klubiniecki You could share the screenshot of the dark theme UI here :+1: :ok_hand:

**Comment by wildan3105** [comment]
Hi @klubiniecki, would you like to continue solving this issue? I'm glad if you'd take a look into this. Thanks!
