### ISSUE TITLE
Languages containing non url friendly characters

### ISSUE THREAD

**Issue by eliassjogreen** [wildan3105/github-langs#84]
**Current behavior:**
The bug happens when you click the link in the bar graph to a language that uses non url friendly characters such as `#` in the language `c#`. This makes the link to the repos page of the user incorrect and not showing any of the repos that actually use that language.

**Expected behavior:**
Without the bug the link to the list of repos would be correct and use the right url encoding.
For example `https://github.com/username?tab=repositories&type=&language=C#` would be `https://github.com/eliassjogreen?tab=repositories&type=&language=C%23`. To fix this simply turn the string for the language into a url friendly string.

**Steps to reproduce:**
To reproduce this you can simply go to a user with for example a c# project and click on the bar for c# and go the that page, as you can see then the url will be wrong and the page will say `username doesn’t have any repositories that match.`.

**Comment by wildan3105** [comment]
Hi @eliassjogreen, thanks for the issue! I'll be very happy if you'd like to open a PR regarding this issue since at this time I don't have much time for this project. Thank you 👍

**Comment by wildan3105** [comment]
Fixed by https://github.com/wildan3105/github-langs/commit/560c5abbc98702a7964d4cea2744758403482304
