### ISSUE TITLE
Modify footer

### ISSUE THREAD

**Issue by wildan3105** [wildan3105/github-langs#92]
**Current behavior:**
Footer : DISCLAIMER : THIS SITE IS A FAN MADE AND NOT AFFILIATED WITH GITHUB.

**Expected behavior:**
Include copyright & year and disclaimer

**Steps to reproduce:**
Check on the website.

**Comment by jarretbryan** [comment]
I can grab this if unclaimed

**Comment by wildan3105** [comment]
Okay go on @jarretbryan !

**Comment by wildan3105** [comment]
Thank you for your contribution! @jarretbryan Very appreciated!
