### ISSUE TITLE
Fix position of badge & emoticon on result

### ISSUE THREAD

**Issue by wildan3105** [wildan3105/github-langs#93]
**Current behavior:**
When displaying result from organization, emoticons & badge are overposition each other.
![github-langs-result](https://user-images.githubusercontent.com/7030099/46710570-a1f00580-cc72-11e8-84fe-3e1133598504.PNG)

**Expected behavior:**
Dynamic position : when displaying result from personal account & organization account so the badge (if any, for organization only) and emoticons are not overposition each other.

**Steps to reproduce:**
Compare result from personal & organization account.

**Comment by joviij** [comment]
I can take a look at this!

**Comment by wildan3105** [comment]
Okay @joviij 👍

**Comment by joviij** [comment]
@wildan3105 Hey, have you ever gotten the error: "This site can’t provide a secure connection" whenever you try to connect to localhost:5000?

**Comment by wildan3105** [comment]
Opps sorry, I force to serve using https. You could solve this by comment at line 12 of `app.js` : 
`app.use(enforce.HTTPS({ trustProtoHeader: true }));`

**Comment by wildan3105** [comment]
Solved by #97
